### ISSUE TITLE
hi, there is a bug when running almost finish

### ISSUE THREAD

**Issue by ersanliqiao** [VoVAllen/tf-dlpack#18]
![image](https://user-images.githubusercontent.com/8411769/110731348-1de44280-825d-11eb-954f-d4ed3e20b5d7.png)

**Comment by ersanliqiao** [comment]
tf2.3

**Comment by VoVAllen** [comment]
DLPack is officially supported in tf 2.3 by `tf.experimental.dlpack.from_dlpack/to_dlpack`. You no longer need this repo. Are you using dgl?

**Comment by ersanliqiao** [comment]
OK, i will try it then. what is dgl?

**Comment by VoVAllen** [comment]
DGL is another project using this repo before

**Comment by ersanliqiao** [comment]
Do you have any example to convert from numba to tensorflow tensor by tf2.3?

**Comment by VoVAllen** [comment]
@ersanliqiao I think numba just use cupy right? Cupy also supports dlpack. Did you meet any problem when using that?

**Comment by ersanliqiao** [comment]
> also

OK，I have done it correctly, thank you very much.
