### ISSUE TITLE
[ERROR] import tfdlpack

### ISSUE THREAD

**Issue by curiosityyy** [VoVAllen/tf-dlpack#8]
(dgl-tf) byli@proj55:~/dgl/examples/tensorflow/gcn$ python
Python 3.7.5 (default, Oct 25 2019, 15:51:11)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dlpack'
>>> import tfdlpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/byli/.conda/envs/dgl-tf/lib/python3.7/site-packages/tfdlpack/__init__.py", line 2, in <module>
    from .core import __version__, to_dlpack, from_dlpack, get_device_and_dtype
  File "/home/byli/.conda/envs/dgl-tf/lib/python3.7/site-packages/tfdlpack/core.py", line 13, in <module>
    dlpack_ops = load_library.load_op_library(libinfo.find_lib_path()[0])
  File "/home/byli/.conda/envs/dgl-tf/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/byli/.conda/envs/dgl-tf/lib/python3.7/site-packages/tfdlpack/libtfdlpack.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by curiosityyy** [comment]
when I import tfdlpack, I got this error.

**Comment by jermainewang** [comment]
What's the version of your tensorflow?

**Comment by curiosityyy** [comment]
tensorflow-estimator 2.0.1
tensorflow-gpu       2.0.0
tfdlpack-gpu         0.1

Minjie Wang <notifications@github.com> 于2019年12月12日周四 下午11:15写道：

**Comment by curiosityyy** [comment]
(dgl-tf) byli@proj55:~/.conda/envs/dgl-tf/lib/python3.7/site-packages/tfdlpack$ ldd  /data/home/byli/.conda/envs/dgl-tf/lib/python3.7/site-packages/tfdlpack/libtfdlpack.so
        linux-vdso.so.1 (0x00007ffeda526000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faf17db8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faf17bb4000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007faf179ac000)
        libtensorflow_framework.so.2 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faf17623000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faf1740b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faf1701a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faf18269000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faf16c7c000)

**Comment by curiosityyy** [comment]
I change the LD_LIBRARY_PATH, and now libtensorflow_framework.so.2 is found. But the error still occurs.

**Comment by jermainewang** [comment]
@curiosityyy The problem should be fixed in #9 and a new release v0.1.1 has been pushed. Please upgrade tfdlpack and let us know if anything is wrong.

**Comment by curiosityyy** [comment]
Thanks. Now it works.

**Comment by kimjh12** [comment]
This problem still occurs with v0.1.3, anyway solved by reinstalling tensorflow with pip rather than conda.

**Comment by VoVAllen** [comment]
@kimjh12 dlpack is now supported in the official tensorflow. You can get it by `tf.experimental.dlpack.to_dlpack/from_dlpack`. I suggest using the latest nightly build, or at least 2.2 version.
